# Generated by Django 3.0.5 on 2020-04-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_bonus', models.IntegerField(default=0)),
                ('referral', models.BooleanField(default=False)),
                ('min_mthly_pay_in', models.IntegerField(default=0)),
                ('req_dd', models.IntegerField(default=0)),
                ('extra_perks', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='Offer start date')),
                ('end_date', models.DateTimeField(verbose_name='Offer end date')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Bank')),
            ],
        ),
    ]
