# Generated by Django 3.0.5 on 2020-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='url',
            field=models.CharField(default='https://www.barclays.co.uk/current-accounts/switch-bank-account/', max_length=250),
        ),
    ]
