# Generated by Django 3.0.5 on 2020-04-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_offer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='MedalType',
            field=models.CharField(blank=True, choices=[('Barclays', 'Barclays')], max_length=100),
        ),
    ]
