# Generated by Django 3.0.5 on 2020-04-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_offer_medaltype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='MedalType',
            new_name='medalType',
        ),
    ]
