# Generated by Django 3.0.5 on 2020-04-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200419_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default="Adrian's Crazy sale", max_length=200),
        ),
    ]
