# Generated by Django 3.0.5 on 2020-04-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20200419_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='title',
        ),
    ]
