# Generated by Django 3.0.5 on 2020-04-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_remove_offer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='offer',
            name='fees_comment',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='offer',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='monthly_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='offer',
            name='monthly_bonus_cmt',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='offer',
            name='monthly_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offer',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_url',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='offer',
            name='extra_perks',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_mthly_pay_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='offer',
            name='switch_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
